services:
  app:
    image: glados_api:0.1.5
    pull_policy: never
    container_name: glados_api
    ports:
      - "7000:8000"

    environment:
      TZ: Europe/Rome
      PYTHONPATH: /app
      UV_NO_DEV: "1"
      # example variables
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      SEARXNG_URL: http://192.168.1.4:8899
      VIKUNJA_BASE_URL: http://192.168.1.4:3456/api/v1
      VIKUNJA_TOKEN: ${VIKUNJA_TOKEN}
      HOME_ASSISTANT_BASE_URL: http://192.168.1.144:8123
      HOME_ASSISTANT_TOKEN: ${HOME_ASSISTANT_TOKEN}

    volumes:
      - ./db/llm_cache.db:/app/db/llm_cache.db

    restart: unless-stopped
